@RestApi_HostAddress = http://localhost:5043

### List users
GET {{RestApi_HostAddress}}/api/v1/employee
Accept: application/json

### Create user
POST {{RestApi_HostAddress}}/api/v1/employee
Content-Type: application/json
{
    "name": "Test create",
    "age": 30,
    "photo": null"
}

### Update user
PUT {{RestApi_HostAddress}}/api/v1/employee
Content-Type: application/json
{
    "photo": null"
}

### Delete user
DELETE {{RestApi_HostAddress}}/api/v1/employee